---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-10.04
  run_list:
  - recipe[apt]
- name: centos-6.3
  run_list:
  - recipe[yum::epel]
suites:
- name: default
  run_list:
  - recipe[hubot]
  attributes: {}
